### PR TITLE
Made Instructor Report Improvements

### LINKED ISSUE #1: FEATURE: UX/UI Improvements to Instructor Report page
# User Story

* As an instructor
* I can see an improved user interface on the instructor report page 
* So that I can I have an improved user experience

### Discussion

On the instructor report page, dollar amounts are not formatted as currency the way they are on the leaderboard page:

Compare:

image

vs.

image

We'd like dollar amounts formatted as currency, and we'd like other numbers right justified rather than left justified in their columns.

### Acceptance Criteria

- [ ] Dollar amounts on instructor report page are displayed as currency
- [ ] Other numbers are right justified.

### Implementation Todos

Should be a change to the react component that renders the instructor report page.

### PR DESCRIPTION
**Pull request by KarimBenyassine1**
## Overview

In this PR, I formatted all dollar amounts as USD currency and right aligned them in their cells.

## Screenshot
Before:
Screen Shot 2023-11-24 at 7 26 00 PM

After
Screen Shot 2023-11-25 at 3 20 31 PM

https://ucsb-cs156-f23.github.io/proj-happycows-f23-5pm-3/prs/21/storybook/?path=/story/components-reports-reportheadertable--one-report

https://ucsb-cs156-f23.github.io/proj-happycows-f23-5pm-3/prs/21/storybook/?path=/story/components-reports-reportlinetable--one-report

https://ucsb-cs156-f23.github.io/proj-happycows-f23-5pm-3/prs/21/storybook/?path=/story/components-reports-reporttable--three-reports

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to Manage Jobs.
4. Generate Instructor Report.
5. Go to Instructor Reports.
6. Click any of the Instruction Reports.
7. Verify improvments.

## Tests

- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 

## Linked Issues

Closes #1

### CODE REVIEW

**Comment by pconrad** [comment]
@KarimBenyassine1 One of the acceptance criteria for #1  is this:

image

We can merge this for 5 points, but you'd need to remove "Closes #1" because we still need another PR to right align the other numbers on the report.

Or: you could do it in this PR and we can bump it up to 10 points.  Either way is fine; you decide.

**Review by pconrad — CHANGES_REQUESTED** [review]
Code looks good, but a few  things:
* Can you also set the cow health to a reasonable number of significant digits (say, two or three digits after the decimal at most?)
* Can you update the screenshots?
* Can you link to a live storybook entry for this page?

**Review by bobert-2 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
